echo Enetring .bootloader...
cd ./bootloader
echo Compiling source if needed...
make
echo Enering root folder...
cd ..
echo Writing OS to virtual disk...
dd if=bootloader/boot.bin of=myos.img
echo Starting OS...
qemu-system-i386 myos.img
